# Generated by Django 3.1.2 on 2020-10-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="like",
            field=models.IntegerField(default=0),
        ),
    ]
